routes/web.php
<?php

use App\Character;
use App\Location;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route models...
Route::model("character", Character::class);
Route::model("location", Location::class);

Route::get('/character/{character}/location/{location}/move', 'CharacterController@getMove')
    ->name('character.move');

Route::get('/character/{character}/attack', 'CharacterController@getAttack')
    ->name('character.attack');

// Simple routes...
Route::group(['middleware' => 'guest'], function () {
    Route::get('/', function () {
        return view('pages.index');
    })->name('index');
});

Route::group(['middleware' => ['auth', 'has.character']], function () {
    Route::get('/home', function () {
        $location = Auth::user()->character->location;
        return redirect()->route('location.show', compact('location'));
    })->name('home');
});

Auth::routes();

// Route resources...
Route::resource("character", "CharacterController");
Route::resource("location", "LocationController");
Route::resource("battle", "BattleController");

app/Location.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @property integer id
 */
class Location extends Model
{
    static protected $oppositeDirections = [
        'north' => 'south',
        'east' => 'west',
    ];

    /**
     * Getting all possible movement directions.
     *
     * @return array
     */
    static public function getDirections()
    {
        return array_merge(array_keys(Location::$oppositeDirections), array_values(Location::$oppositeDirections));
    }

    /**
     * Getting the opposite direction
     *
     * @param $direction
     *
     * @return mixed
     */
    static protected function getAppositeDirection($direction)
    {
        if (array_key_exists ($direction, self::$oppositeDirections)) {
            return self::$oppositeDirections[$direction];
        }

        if (in_array($direction, self::$oppositeDirections)) {
            return array_search($direction, self::$oppositeDirections);
        }

        throw new \InvalidArgumentException('Invalid direction: '.$direction);
    }

    /**
     * @param $direction
     *
     * @return bool
     */
    static protected function isValidDirection($direction)
    {
        return array_key_exists ($direction, self::$oppositeDirections) || in_array($direction, self::$oppositeDirections);
    }

    /**
     * Get the characters at the location.
     *
     * @return HasMany
     */
    public function characters()
    {
        return $this->hasMany(Character::class);
    }

    /**
     * @return BelongsToMany
     */
    public function adjacentLocations()
    {
        return $this->belongsToMany(Location::class, 'adjacent_location', 'location_id', 'adjacent_location_id');
    }

    /**
     * Get the adjacent location to the north of the current location.
     *
     * @param $type
     * @return mixed
     */
    public function adjacent($type)
    {
        return $this->adjacentLocations()->wherePivot('direction', $type)->first();
    }

    /** TODO: maybe for later use */
    /**
     * @param Location $adjacent
     * @param $direction
     */
    public function addAdjacentLocation(Location $adjacent, $direction)
    {
        if (!self::isValidDirection($direction)) {
            throw new \InvalidArgumentException('Invalid adjacent direction type: '.$direction);
        }

        $this->adjacentLocations()->attach($adjacent, [
            'direction' => $direction,
            "created_at"            => Carbon::now(),
            "updated_at"            => Carbon::now(),
        ]); // add adjacent

        $adjacent->adjacentLocations()->attach($this, [
            'direction' => self::getAppositeDirection($direction),
            "created_at"            => Carbon::now(),
            "updated_at"            => Carbon::now(),
        ]); // add yourself, too
    }

    /**
     * @param Location $adjacent
     */
    public function removeAdjacentLocation(Location $adjacent)
    {
        $this->adjacentLocations()->detach($adjacent);   // remove friend
        $adjacent->adjacentLocations()->detach($this);  // remove yourself, too
    }
}

app/Http/Controllers/LocationController.php
<?php

namespace App\Http\Controllers;

use App\Location;

class LocationController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth', ['only' => ['show']]);
        $this->middleware('has.character', ['only' => ['show']]);
        $this->middleware('character.location', ['only' => ['show']]);
    }

    /**
     * Display the specified resource.
     *
     * @param Location $location
     * @return \Illuminate\Http\Response
     */
    public function show(Location $location)
    {
        return view('location.show', compact('location'));
    }
}

resources/views/location/show.blade.php
@extends("base")

@section("head")
    <title>{{ $location->name }}</title>
    @parent
@stop

@section("body")

    <div class="col-md-6">
        <h2>{{ $location->name }}</h2>
        <hr>
        <p>{{ $location->description }}</p>
        <img class="img-responsive col-md-8 col-md-offset-2" src="{{ asset('images/'.$location->image) }}">

        <div class="col-md-12">
            <ul class="list-unstyled">
                @if(!is_null($adjacent = $location->adjacent('north')))
                    <li>
                        <a href="{{ route('character.move', ['character' => Auth::user()->character, 'location' => $adjacent]) }}">
                            {{ $adjacent->name }}
                            <span class="glyphicon glyphicon-arrow-up"></span>
                        </a>
                    </li>
                @endif
                @if(!is_null($adjacent = $location->adjacent('east')))
                    <li>
                        <a href="{{ route('character.move', ['character' => Auth::user()->character, 'location' => $adjacent]) }}">
                            {{ $adjacent->name }}
                            <span class="glyphicon glyphicon-arrow-right"></span>
                        </a>
                    </li>
                @endif
                @if(!is_null($adjacent = $location->adjacent('south')))
                    <li>
                        <a href="{{ route('character.move', ['character' => Auth::user()->character, 'location' => $adjacent]) }}">
                            {{ $adjacent->name }}
                            <span class="glyphicon glyphicon-arrow-down"></span>
                        </a>
                    </li>
                @endif
                @if(!is_null($adjacent = $location->adjacent('west')))
                    <li>
                        <a href="{{ route('character.move', ['character' => Auth::user()->character, 'location' => $adjacent]) }}">
                            {{ $adjacent->name }}
                            <span class="glyphicon glyphicon-arrow-left"></span>
                        </a>
                    </li>
                @endif
            </ul>
        </div>
    </div>

    <div class="col-md-6">
        <h2>Characters at this location:</h2>
        <hr>
        <ul class="list-group">
            <?php $icon = ''; ?>
            @foreach($location->characters as $character)
                <?php
                    /** @var \App\Character $character **/
                    $class = 'list-group-item-warning';
                    $description = '(NPC)';

                    if (!$character->isNPC() ) {
                        $description = $character->isYou() ? '(you)' : '';
                        $class = $character->isYou() ? 'active' : '';
                    }
                ?>
                <li href="#" class="list-group-item {{ $class }}">
                    @if($character->gender == 'male')
                        <span class="fa fa-mars"></span>
                    @else
                        <span class="fa fa-venus"></span>
                    @endif

                    <a href="{{ route('character.show', ['character' => $character]) }}">
                        @component('components.short_character_description', compact('character'))
                            {{ $description }}
                        @endcomponent
                    </a>

                    @if(!$character->isYou())
                        <a href="{{ route('character.attack', ['character' => $character]) }}" class="pull-right">
                            <span class="fa fa-flash"></span> attack
                        </a>
                    @endif

                </li>
            @endforeach
        </ul>
    </div>

@stop