routes/web.php
<?php

use App\Character;
use App\Location;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route models...
Route::model("character", Character::class);
Route::model("location", Location::class);

Route::get('/character/{character}/location/{location}/move', 'CharacterController@getMove')
    ->name('character.move');

Route::get('/character/{character}/attack', 'CharacterController@getAttack')
    ->name('character.attack');

// Simple routes...
Route::group(['middleware' => 'guest'], function () {
    Route::get('/', function () {
        return view('pages.index');
    })->name('index');
});

Route::group(['middleware' => ['auth', 'has.character']], function () {
    Route::get('/home', function () {
        $location = Auth::user()->character->location;
        return redirect()->route('location.show', compact('location'));
    })->name('home');
});

Auth::routes();

// Route resources...
Route::resource("character", "CharacterController");
Route::resource("location", "LocationController");
Route::resource("battle", "BattleController");

app/Character.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * @property User user
 * @property Location location
 * @property integer id
 * @property integer hit_points
 * @property integer xp
 * @property Level level
 * @property integer available_attribute_points
 * @property integer battles_won
 * @property integer battles_lost
 * @property integer strength
 * @property integer agility
 */
class Character extends Model
{

    protected $guarded = ['user_id'];

    /**
     * Get the user of the character
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function level()
    {
        return $this->belongsTo(Level::class);
    }

    /**
     * Get the user of the character
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the user of the character
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function race()
    {
        return $this->belongsTo(Race::class);
    }

    /**
     * Get the current location of the character
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function location()
    {
        return $this->belongsTo(Location::class);
    }

    /**
     * @return bool
     */
    public function isYou()
    {
        return (!$this->isNPC()) && $this->user->id == Auth::user()->id;
    }

    /**
     * Check if the character is an Non Player Character ( user_id field is null )
     *
     * @return bool
     */
    public function isNPC()
    {
        return is_null($this->user);
    }
}

app/Http/Controllers/CharacterController.php
<?php

namespace App\Http\Controllers;

use App\Battle;
use App\Character;
use App\Http\Requests\CreateCharacterRequest;
use App\Http\Requests\MoveCharacterRequest;
use App\Http\Requests\UpdateCharacterAttributeRequest;
use App\Location;
use App\Race;
use App\RuleSets\CharacterRuleSet;
use App\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;

class CharacterController extends Controller
{

    /**
     * CharacterController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth', ['only' => ['create', 'store', 'getMove', 'update']]);
        $this->middleware('has.character', ['only' => ['getMove', 'update']]);
        $this->middleware('owns.character', ['only' => ['update']]);
        $this->middleware('no.character', ['only' => ['create', 'store']]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $races = Race::all();
        $user = Auth::user();
        return view('character.create', compact('races', 'user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateCharacterRequest $request
     * @param CharacterRuleSet $characterRuleSet
     *
     * @return Response
     */
    public function store(CreateCharacterRequest $request, CharacterRuleSet $characterRuleSet)
    {
        $character = $characterRuleSet->createCharacter($request);

        return redirect()->route("home");
    }

    /**
     * Display the specified resource.
     *
     * @param Character $character
     * @return Response
     */
    public function show(Character $character)
    {
        return view('character.show', compact('character'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateCharacterAttributeRequest $request
     * @param Character $character
     *
     * @return Response
     */
    public function update(UpdateCharacterAttributeRequest $request, Character $character)
    {
        $attribute = $request->input('attribute');

        if ($character->available_attribute_points) {
            $character->available_attribute_points--;
            $character->$attribute++;
            $character->save();
        }

        return view('character.show', compact('character'));
    }

    /**
     * @param Character $character
     * @param Location $location
     * @param MoveCharacterRequest $request
     *
     * @return RedirectResponse
     */
    public function getMove(Character $character, Location $location, MoveCharacterRequest $request)
    {
        // update character's location
        $character->location()->associate($location)->save();

        return redirect()->route('location.show', compact('location'));
    }

    /**
     * @param Character $defender
     * @param Request $request
     * @param CharacterRuleSet $characterRuleSet
     *
     * @return RedirectResponse
     */
    public function getAttack(Character $defender, Request $request, CharacterRuleSet $characterRuleSet)
    {
        $authenticatedUser = $request->user(); /** @var User $authenticatedUser */
        $attacker = $authenticatedUser->character;

        /** @var Battle $battle */
        $battle = $characterRuleSet->attack($attacker, $defender);

        return redirect()->route('battle.show', compact('battle'));
    }
}

resources/views/character/create.blade.php
@extends("base")

@section("head")
    <title>Create Character</title>
    @parent
@stop

@section("body")
    <div class="row">
        <div class="col-md-4 col-md-offset-1 col-sm-6 carousel carousel-race hidden-xs" data-interval="false">
            <!-- Race Image slides -->
            <div class="carousel-inner" role="listbox">
                @foreach($races as $i => $race)
                <div class="item{{ ($i == 0) ? ' active' : '' }}">
                    <img class="img-race img-male" src="{{ asset('images/'.$race->male_image) }}">
                    <img class="img-race img-female" src="{{ asset('images/'.$race->female_image) }}" style="display: none;">
                    <div class="carousel-caption">
                        <h3>{{ $race->name }}</h3>
                        <p>{{ $race->description }}</p>
                    </div>
                </div>
                @endforeach
            </div>
        </div>
        <div class="col-md-4 col-md-offset-1 col-sm-6">
            <form role="form" method="POST" action="{{ URL::route('character.store') }}">
                {!! csrf_field() !!}
                <input type="hidden" name="race_id" id="race_id" value="{{ $races[0]->id }}">
                <input type="hidden" name="gender" id="gender" value="male">

                <h2>Please create your game character</h2>
                <div class="form-group">
                    <div>
                        <label for="name" class="sr-only">Name</label>
                        <input type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="Name" required="" autofocus="">
                    </div>
                </div>
                <div class="form-group carousel carousel-race" id="race-carousel" data-interval="false">
                    <!-- Race Name slides -->
                    <div class="carousel-inner" role="listbox">
                        @foreach($races as $i => $race)
                        <div class="item{{ ($i == 0) ? ' active' : '' }}" id="race-id-{{ $race->id }}">
                            <div class="carousel-content">
                                <h3>{{ $race->name }}</h3>
                            </div>
                        </div>
                        @endforeach
                    </div>

                    <!-- Left and right controls -->
                    <a class="left left-race carousel-control" href="#race-carousel" role="button">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>

                    <a class="right right-race carousel-control" href="#race-carousel" role="button">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>

                </div>
                <div class="form-group carousel carousel-gender" id="gender-carousel" data-interval="false">
                    <!-- Gender slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active" id="male">
                            <div class="carousel-content">
                                <h3>Male</h3>
                            </div>
                        </div>
                        <div class="item" id="female">
                            <div class="carousel-content">
                                <h3>Female</h3>
                            </div>
                        </div>
                    </div>

                    <!-- Left and right controls -->
                    <a class="left left-gender carousel-control" href="#gender-carousel" role="button">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>

                    <a class="right right-gender carousel-control" href="#gender-carousel" role="button">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>

                </div>
                <div class="form-group carousel carousel-race" id="race-carousel" data-interval="false">
                    <!-- Race Stats slides -->
                    <div class="carousel-inner" role="listbox">
                        @foreach($races as $i => $race)
                        <div class="item{{ ($i == 0) ? ' active' : '' }} carousel-content table-responsive table-attributes">
                            <table class="table">
                                <tr>
                                    <th>Strength</th>
                                    <td>{{ $race->strength }}</td>
                                </tr>
                                <tr>
                                    <th>Agility</th>
                                    <td>{{ $race->agility }}</td>
                                </tr>
                                <tr>
                                    <th>Constitution</th>
                                    <td>{{ $race->constitution }}</td>
                                </tr>
                                <tr>
                                    <th>Intelligence</th>
                                    <td>{{ $race->intelligence }}</td>
                                </tr>
                                <tr>
                                    <th>Charisma</th>
                                    <td>{{ $race->charisma }}</td>
                                </tr>
                            </table>
                        </div>
                        @endforeach
                    </div>

                </div>

                <div>
                    <button type="submit" class="btn btn-success btn-block">Create Character</button>
                </div>
            </form>
        </div>
    </div>

@stop

@section("footer")
    @parent

    <script src="{{ asset('js/character-create.js') }}"></script>
@stop

resources/views/character/show.blade.php
@extends("base")

@section("head")
    <title>{{ $character->name }} (Level: {{ $character->level->id }})</title>
    @parent
@stop

@section("body")
    <div class="row">

        <!-- Left Side -->
        <div class="col-md-4 col-md-offset-1 col-sm-6 hidden-xs">

            <h2>{{ $character->name }} ({{ $character->hit_points }} / {{ $character->total_hit_points }})</h2>

            <img class="img-race" src="{{ asset('images/' . $character->race->male_image) }}">
        </div>


        <!-- Right Side -->
        <div class="col-md-4 col-md-offset-1 col-sm-6">

                <table class="table table-responsive">
                    <caption>General</caption>
                    <tr>
                        <th>Race</th>
                        <td>{{ $character->race->name }}</td>
                    </tr>
                    <tr>
                        <th>Level</th>
                        <td>{{ $character->level->id }}</td>
                    </tr>
                    <tr>
                        <th>XP</th>
                        <td><progress max="{{ $character->level->next_level_xp_threshold }}" value="{{ $character->xp }}"></progress></td>
                    </tr>
                </table>

            <?php
                $hasFreePoints = ($character->isYou() && $character->available_attribute_points);
            ?>

            @if($hasFreePoints)
            <form role="form" method="POST" action="{{ URL::route('character.update', $character) }}" id="increment_attribute">
                {{ method_field('PUT') }}
                {!! csrf_field() !!}

                <input type="hidden" id="attribute_input" name="attribute" value="strength">
            @endif

                <table class="table table-responsive table-attributes">
                    <caption>Attributes</caption>
                    <tr>
                        <th>Strength</th>
                        <td>{{ $character->strength }}</td>
                        @component('components.increment_attribute_button', compact('hasFreePoints'))
                            {{ 'strength' }}
                        @endcomponent
                    </tr>
                    <tr>
                        <th>Agility</th>
                        <td>{{ $character->agility }}</td>
                        @component('components.increment_attribute_button', compact('hasFreePoints'))
                            {{ 'agility' }}
                        @endcomponent
                    </tr>
                    <tr>
                        <th>Constitution</th>
                        <td>{{ $character->constitution }}</td>
                        @component('components.increment_attribute_button', compact('hasFreePoints'))
                            {{ 'constitution' }}
                        @endcomponent
                    </tr>
                    <tr>
                        <th>Intelligence</th>
                        <td>{{ $character->intelligence }}</td>
                        @component('components.increment_attribute_button', compact('hasFreePoints'))
                            {{ 'intelligence' }}
                        @endcomponent
                    </tr>
                    <tr>
                        <th>Charisma</th>
                        <td>{{ $character->charisma }}</td>
                        @component('components.increment_attribute_button', compact('hasFreePoints'))
                            {{ 'charisma' }}
                        @endcomponent
                    </tr>

                    @if($hasFreePoints)
                        <tfoot>
                            <th>Available points</th>
                            <td class="circle">{{ $character->available_attribute_points }}</td>
                        </tfoot>
                    @endif

                </table>

            @if($hasFreePoints)
                </form>
            @endif

                <table class="table table-responsive">
                    <caption>Statistics</caption>
                    <tr>
                        <th>Reputation</th>
                        <td>{{ $character->reputation }}</td>
                    </tr>
                    <tr>
                        <th>Money</th>
                        <td>{{ $character->money }}</td>
                    </tr>
                    <tr>
                        <th>Battles Won</th>
                        <td>{{ $character->battles_won }}</td>
                    </tr>
                    <tr>
                        <th>Battles Lost</th>
                        <td>{{ $character->battles_lost }}</td>
                    </tr>
                </table>

            <a href="{{ route('location.show', ['location' => $character->location]) }}">
                Back to {{ $character->location->name }}
                <span class="fa fa-history"></span>
            </a>
        </div>
    </div>

@stop

@section("footer")
    @parent

    <script src="{{ asset('js/character-update.js') }}"></script>
@stop